# docker/Dockerfile.parser
FROM python:3.11-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1 \
	PYTHONPATH=/ICU-MUJICA

RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	build-essential \
	curl \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /ICU-MUJICA

RUN mkdir -p /ICU-MUJICA/shared_workspace /ICU-MUJICA/output /ICU-MUJICA/src && chmod -R 777 /ICU-MUJICA

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN chmod -R a+rX /usr/local/lib/python3.11/site-packages
RUN chmod -R a+rx /usr/local/bin/

COPY ./src /ICU-MUJICA/src

WORKDIR /ICU-MUJICA
ENV PYTHONPATH=/ICU-MUJICA

CMD ["uvicorn", "src.parser.main:app", "--host", "0.0.0.0", "--port", "8000"]